name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 Explore-GitHub-Actions:
  runs-on: ubuntu-latest
  steps:
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node-version }}
  - name: Check out repository code
     uses: actions/checkout@v4
  - name: Install dependencies
     run: npm install
  - name: Run dev
    run: npm run dev
  - name: Run build
    run: npm run build
  - name: Run start
    run: npm run start
  - name: Run lint
    run: npm run lint
   